-- Administrador 2.1 (beta ainda kakaka)
-- Créditos: RDSK.DNZ.O ZE
-- Generated by LuaCoder

-------------------- SERVICES --------------------
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local LocalPlayer = Players.LocalPlayer
local Camera = workspace.CurrentCamera

-------------------- GUI BASE --------------------
local gui = Instance.new("ScreenGui")
gui.Name = "Administrador14"
gui.ResetOnSpawn = false
gui.Parent = LocalPlayer:WaitForChild("PlayerGui")

-- Botão R (abrir)
local openBtn = Instance.new("TextButton", gui)
openBtn.Size = UDim2.fromOffset(40,40)
openBtn.Position = UDim2.new(0,10,0.5,-20)
openBtn.Text = "R"
openBtn.TextColor3 = Color3.new(1,0,0)
openBtn.BackgroundColor3 = Color3.fromRGB(40,40,40)

-- Menu principal
local main = Instance.new("Frame", gui)
main.Size = UDim2.fromOffset(650,420)
main.Position = UDim2.new(0.5,-325,0.5,-210)
main.BackgroundColor3 = Color3.fromRGB(120,120,120)
main.Visible = false

-- Fechar
local close = Instance.new("TextButton", main)
close.Size = UDim2.fromOffset(30,30)
close.Position = UDim2.new(1,-35,0,5)
close.Text = "X"
close.TextColor3 = Color3.new(1,0,0)
close.BackgroundColor3 = Color3.fromRGB(70,70,70)

-------------------- ABAS --------------------
local tabBar = Instance.new("Frame", main)
tabBar.Size = UDim2.fromOffset(130,360)
tabBar.Position = UDim2.fromOffset(10,40)
tabBar.BackgroundColor3 = Color3.fromRGB(90,90,90)

local function newTab()
	local f = Instance.new("Frame", main)
	f.Size = UDim2.fromOffset(300,360)
	f.Position = UDim2.fromOffset(150,40)
	f.BackgroundTransparency = 1
	f.Visible = false
	return f
end

local tabs = {
	Opcoes = newTab(),
	Troll = newTab(),
	Trapacas = newTab()
}

local function tabButton(text, y, tab)
	local b = Instance.new("TextButton", tabBar)
	b.Size = UDim2.fromOffset(110,35)
	b.Position = UDim2.fromOffset(10,y)
	b.Text = text
	b.BackgroundColor3 = Color3.fromRGB(150,0,0)
	b.TextColor3 = Color3.new(1,1,1)
	b.MouseButton1Click:Connect(function()
		for _,v in pairs(tabs) do v.Visible = false end
		tab.Visible = true
	end)
end

tabButton("💡 Opções", 10, tabs.Opcoes)
tabButton("😼 Troll", 55, tabs.Troll)
tabButton("☠️ Trapaças", 100, tabs.Trapacas)
tabs.Opcoes.Visible = true

-------------------- LISTA DE PLAYERS --------------------
local selectedPlayer = nil
local list = Instance.new("ScrollingFrame", main)
list.Size = UDim2.fromOffset(140,360)
list.Position = UDim2.fromOffset(500,40)
list.ScrollBarThickness = 6

local function refreshPlayers()
	list:ClearAllChildren()
	local y = 0
	for _,p in pairs(Players:GetPlayers()) do
		if p ~= LocalPlayer then
			local b = Instance.new("TextButton", list)
			b.Size = UDim2.fromOffset(130,30)
			b.Position = UDim2.fromOffset(5,y)
			b.Text = p.Name
			b.BackgroundColor3 = Color3.fromRGB(80,80,80)
			b.TextColor3 = Color3.new(1,1,1)
			b.MouseButton1Click:Connect(function()
				selectedPlayer = p
			end)
			y += 35
		end
	end
	list.CanvasSize = UDim2.fromOffset(0,y)
end
refreshPlayers()
Players.PlayerAdded:Connect(refreshPlayers)
Players.PlayerRemoving:Connect(refreshPlayers)

-------------------- BOTÃO PADRÃO --------------------
local function btn(parent,text,y)
	local b = Instance.new("TextButton", parent)
	b.Size = UDim2.fromOffset(280,30)
	b.Position = UDim2.fromOffset(10,y)
	b.Text = text
	b.BackgroundColor3 = Color3.fromRGB(150,0,0)
	b.TextColor3 = Color3.new(1,1,1)
	return b
end

-------------------- OPÇÕES 💡 --------------------
-- Fly
local flyOn = false
local gyro, vel
btn(tabs.Opcoes,"Fly ☠️",10).MouseButton1Click:Connect(function()
	flyOn = not flyOn
	local hrp = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
	if flyOn and hrp then
		gyro = Instance.new("BodyGyro",hrp)
		vel = Instance.new("BodyVelocity",hrp)
		gyro.P = 9e4
		vel.MaxForce = Vector3.new(9e4,9e4,9e4)
	else
		if gyro then gyro:Destroy() end
		if vel then vel:Destroy() end
	end
end)

RunService.RenderStepped:Connect(function()
	if flyOn and vel and gyro then
		vel.Velocity = Camera.CFrame.LookVector * 50
		gyro.CFrame = Camera.CFrame
	end
end)

-- Noclip
local noclipOn = false
btn(tabs.Opcoes,"Noclip 😼",50).MouseButton1Click:Connect(function()
	noclipOn = not noclipOn
end)

RunService.Stepped:Connect(function()
	if noclipOn and LocalPlayer.Character then
		for _,v in pairs(LocalPlayer.Character:GetDescendants()) do
			if v:IsA("BasePart") then v.CanCollide = false end
		end
	end
end)

-- Speed Hack
local speedBox = Instance.new("TextBox", tabs.Opcoes)
speedBox.Size = UDim2.fromOffset(280,30)
speedBox.Position = UDim2.fromOffset(10,90)
speedBox.PlaceholderText = "Speed (0 - inf)"
speedBox.FocusLost:Connect(function()
	local hum = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("Humanoid")
	local val = tonumber(speedBox.Text)
	if hum and val then hum.WalkSpeed = val end
end)

-- TP Tool
btn(tabs.Opcoes,"TP Tool 🌀",130).MouseButton1Click:Connect(function()
	local tool = Instance.new("Tool")
	tool.Name = "TP Tool"
	tool.RequiresHandle = false
	tool.Parent = LocalPlayer.Backpack
	tool.Activated:Connect(function()
		local mouse = LocalPlayer:GetMouse()
		if mouse.Hit then
			LocalPlayer.Character:MoveTo(mouse.Hit.Position)
		end
	end)
end)

-- Respawn
btn(tabs.Opcoes,"Respawn",170).MouseButton1Click:Connect(function()
	LocalPlayer.Character:BreakJoints()
end)

-------------------- TROLL 😼 (BETA) --------------------
-- View
local viewing = false
btn(tabs.Troll,"View Player (Beta)",10).MouseButton1Click:Connect(function()
	if not selectedPlayer then return end
	viewing = not viewing
	if viewing then
		Camera.CameraSubject = selectedPlayer.Character:FindFirstChild("Humanoid")
	else
		Camera.CameraSubject = LocalPlayer.Character:FindFirstChild("Humanoid")
	end
end)

-- TP Player
btn(tabs.Troll,"TP Player",50).MouseButton1Click:Connect(function()
	if selectedPlayer and selectedPlayer.Character then
		LocalPlayer.Character:MoveTo(selectedPlayer.Character.HumanoidRootPart.Position)
	end
end)

-- Fling Player
local flingBtn = btn(tabs.Troll,"FLING PLAYER (BETA)",90)
flingBtn.TextColor3 = Color3.new(1,0,0)
flingBtn.MouseButton1Click:Connect(function()
	if selectedPlayer and selectedPlayer.Character then
		local hrp = selectedPlayer.Character:FindFirstChild("HumanoidRootPart")
		if hrp then
			local bv = Instance.new("BodyVelocity",hrp)
			bv.Velocity = Vector3.new(0,300,0) + Camera.CFrame.LookVector * 600
			bv.MaxForce = Vector3.new(9e5,9e5,9e5)
			task.delay(0.3,function() bv:Destroy() end)
		end
	end
end)

-------------------- TRAPAÇAS ☠️ --------------------
-- ESP
local espOn = false
btn(tabs.Trapacas,"ESP",10).MouseButton1Click:Connect(function()
	espOn = not espOn
	for _,p in pairs(Players:GetPlayers()) do
		if p ~= LocalPlayer and p.Character then
			if espOn then
				local h = Instance.new("Highlight",p.Character)
				h.FillColor = Color3.new(1,0,0)
			else
				if p.Character:FindFirstChild("Highlight") then
					p.Character.Highlight:Destroy()
				end
			end
		end
	end
end)

-- ESP Anteninha
btn(tabs.Trapacas,"ESP Anteninha",50).MouseButton1Click:Connect(function()
	for _,p in pairs(Players:GetPlayers()) do
		if p ~= LocalPlayer and p.Character and p.Character:FindFirstChild("Head") then
			if not p.Character.Head:FindFirstChild("Antenna") then
				local a = Instance.new("BoxHandleAdornment")
				a.Name = "Antenna"
				a.Size = Vector3.new(0.1,5,0.1)
				a.Adornee = p.Character.Head
				a.AlwaysOnTop = true
				a.Color3 = Color3.new(1,0,0)
				a.Parent = p.Character.Head
			else
				p.Character.Head.Antenna:Destroy()
			end
		end
	end
end)

-- Aimbot
local aimbotOn = false
btn(tabs.Trapacas,"AIMBOT",90).MouseButton1Click:Connect(function()
	aimbotOn = not aimbotOn
end)

RunService.RenderStepped:Connect(function()
	if aimbotOn and selectedPlayer and selectedPlayer.Character then
		local head = selectedPlayer.Character:FindFirstChild("Head")
		if head then
			Camera.CFrame = CFrame.new(Camera.CFrame.Position, head.Position)
		end
	end
end)

-- X-Ray
local xrayOn = false
btn(tabs.Trapacas,"X-Ray",130).MouseButton1Click:Connect(function()
	xrayOn = not xrayOn
	for _,v in pairs(workspace:GetDescendants()) do
		if v:IsA("BasePart") then
			v.LocalTransparencyModifier = xrayOn and 0.7 or 0
		end
	end
end)

-- Invisível (Beta)
local invisOn = false
btn(tabs.Trapacas,"Invisível (Beta)",170).MouseButton1Click:Connect(function()
	invisOn = not invisOn
	local hrp = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
	if hrp then
		hrp.CFrame = invisOn and hrp.CFrame * CFrame.new(0,-10,0)
			or hrp.CFrame * CFrame.new(0,10,0)
	end
end)

-------------------- ABRIR / FECHAR --------------------
openBtn.MouseButton1Click:Connect(function()
	main.Visible = true
	openBtn.Visible = false
end)
close.MouseButton1Click:Connect(function()
	main.Visible = false
	openBtn.Visible = true
end)

print("Administrador 1.4 (beta) COMPLETO carregado com sucesso")-------------------- ABAS (ADICIONANDO ANTIS) --------------------
-- Adicione "Antis" na sua tabela de abas
tabs.Antis = newTab()
tabButton("🛡️ Antis", 145, tabs.Antis)

-------------------- ANTIS 🛡️ --------------------

-- 1. Anti Fling
-- Explicação: Ele detecta se sua velocidade está alta demais (comum em ataques de fling) e reseta sua velocidade linear/angular.
local antiFlingOn = false
btn(tabs.Antis, "Anti Fling", 10).MouseButton1Click:Connect(function()
    antiFlingOn = not antiFlingOn
    print("Anti Fling: " .. tostring(antiFlingOn))
end)

RunService.Heartbeat:Connect(function()
    if antiFlingOn and LocalPlayer.Character then
        local hrp = LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
        if hrp then
            hrp.RotVelocity = Vector3.new(0, 0, 0)
            hrp.Velocity = Vector3.new(hrp.Velocity.X, hrp.Velocity.Y, hrp.Velocity.Z)
        end
    end
end)

-- 2. Anti Cooldown (BETA)
-- Nota: Isso funciona em ferramentas que usam tempo de espera local. 
-- Em alguns jogos, o tempo é controlado pelo servidor e pode não funcionar 100%.
btn(tabs.Antis, "Anti Cooldown", 50).MouseButton1Click:Connect(function()
    for _, tool in pairs(LocalPlayer.Backpack:GetChildren()) do
        if tool:IsA("Tool") then
            -- Tenta forçar o tempo de espera para zero
            if tool:FindFirstChild("Cooldown") then tool.Cooldown.Value = 0 end
            -- Muitos scripts usam variáveis locais, tentamos resetar o estado da Tool
            tool.Enabled = true
        end
    end
end)

-- 3. Anti AFK
-- Impede que o Roblox te desconecte por inatividade.
btn(tabs.Antis, "Anti AFK", 90).MouseButton1Click:Connect(function()
    local vu = game:GetService("VirtualUser")
    LocalPlayer.Idled:Connect(function()
        vu:Button2Down(Vector2.new(0,0), workspace.CurrentCamera.CFrame)
        task.wait(1)
        vu:Button2Up(Vector2.new(0,0), workspace.CurrentCamera.CFrame)
    end)
    print("Anti AFK Ativado")
end)

-- 4. Anti Lag (Remover Texturas)
-- Deixa o jogo com visual "plastic" para ganhar FPS.
btn(tabs.Antis, "Anti Lag (FPS Boost)", 130).MouseButton1Click:Connect(function()
    local terrain = workspace:FindFirstChildOfClass('Terrain')
    terrain.WaterWaveSize = 0
    terrain.WaterWaveSpeed = 0
    terrain.WaterReflectance = 0
    terrain.WaterTransparency = 0
    
    for _, v in pairs(workspace:GetDescendants()) do
        if v:IsA("BasePart") then
            v.Material = Enum.Material.Plastic
            v.Reflectance = 0
        elseif v:IsA("Decal") or v:IsA("Texture") then
            v:Destroy()
        elseif v:IsA("ParticleEmitter") or v:IsA("Trail") then
            v.Enabled = false
        end
    end
    print("Lag reduzido: Texturas removidas")
end)
-------------------- NOVAS OPÇÕES TROLL 😼 --------------------

-- 4. Bring Player (Trazer o jogador até você)
btn(tabs.Troll, "Bring Player", 130).MouseButton1Click:Connect(function()
    if selectedPlayer and selectedPlayer.Character and LocalPlayer.Character then
        local targetHrp = selectedPlayer.Character:FindFirstChild("HumanoidRootPart")
        local myHrp = LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
        
        if targetHrp and myHrp then
            targetHrp.CFrame = myHrp.CFrame * CFrame.new(0, 0, -3) -- Teleporta ele 3 studs na sua frente
        end
    end
end)

-- 5. Freeze Player (Congelar/Descongelar)
local isFrozen = false
btn(tabs.Troll, "Freeze / Unfreeze", 170).MouseButton1Click:Connect(function()
    if selectedPlayer and selectedPlayer.Character then
        local targetHrp = selectedPlayer.Character:FindFirstChild("HumanoidRootPart")
        if targetHrp then
            isFrozen = not isFrozen
            targetHrp.Anchored = isFrozen
            print(selectedPlayer.Name .. " congelado: " .. tostring(isFrozen))
        end
    end
end)

-- 6. Spin Player (Fazer o alvo girar)
local spinning = false
btn(tabs.Troll, "Spin Player", 210).MouseButton1Click:Connect(function()
    if selectedPlayer and selectedPlayer.Character then
        spinning = not spinning
        local hrp = selectedPlayer.Character:FindFirstChild("HumanoidRootPart")
        if hrp then
            local velocity = hrp:FindFirstChild("SpinVelocity") or Instance.new("BodyAngularVelocity", hrp)
            velocity.Name = "SpinVelocity"
            if spinning then
                velocity.AngularVelocity = Vector3.new(0, 50, 0)
                velocity.MaxTorque = Vector3.new(0, math.huge, 0)
            else
                velocity:Destroy()
            end
        end
    end
end)
-------------------- ABAS (ATUALIZADO) --------------------
-- Adicione "Jogos" na sua tabela de abas
tabs.Jogos = newTab()
tabButton("🎮 Jogos", 190, tabs.Jogos)

-------------------- JOGOS 🎮 --------------------

-- Função que contém o seu script do Escape da Lava
local function executarEscapeLava()
    -- Script: Lendas Brabas Beta + Auto-Farm
    local Player = game.Players.LocalPlayer
    local PlayerGui = Player:WaitForChild("PlayerGui")
    
    local screenGui = Instance.new("ScreenGui")
    screenGui.Name = "LendasBrabasGui"
    screenGui.ResetOnSpawn = false
    screenGui.Parent = PlayerGui

    local frame = Instance.new("Frame")
    frame.Size = UDim2.new(0, 260, 0, 480)
    frame.Position = UDim2.new(0.5, -130, 0.4, -240)
    frame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
    frame.Active = true
    frame.Draggable = true
    frame.Parent = screenGui

    local frameCorner = Instance.new("UICorner", frame)
    frameCorner.CornerRadius = UDim.new(0, 10)

    local title = Instance.new("TextLabel", frame)
    title.Size = UDim2.new(1, 0, 0, 40)
    title.BackgroundTransparency = 1
    title.RichText = true
    title.Text = '<font color="rgb(255, 255, 0)">Lendas Brabas </font><font color="rgb(255, 0, 0)">Beta</font>'
    title.TextSize = 22
    title.Font = Enum.Font.SourceSansBold

    local worlds = game:GetService("Workspace"):WaitForChild("DynamicObjects"):WaitForChild("Worlds")
    local listaTeleportes = {
        {nome = "Wins Level 1", path = worlds.Rainbow.WinPortal.Touch},
        {nome = "Wins Level 2", path = worlds.Volcano.WinPortal.Touch},
        {nome = "Wins Level 3", path = worlds.Frozen.WinPortal.Touch},
        {nome = "Wins Level 4", path = worlds.Space.WinPortal.Touch},
        {nome = "Wins Level 5", path = worlds.Beach.End.Part}
    }

    local autoFarmActive = false
    local autoBtn = Instance.new("TextButton", frame)
    autoBtn.Size = UDim2.new(0.85, 0, 0, 45)
    autoBtn.Position = UDim2.new(0.075, 0, 0, 380)
    autoBtn.Text = "Automatização: DESLIGADO"
    autoBtn.BackgroundColor3 = Color3.fromRGB(200, 0, 0)
    autoBtn.TextColor3 = Color3.new(1, 1, 1)
    autoBtn.Font = Enum.Font.SourceSansBold
    autoBtn.TextSize = 16

    Instance.new("UICorner", autoBtn).CornerRadius = UDim.new(0, 8)

    spawn(function()
        while true do
            task.wait(0.5)
            if autoFarmActive then
                for _, info in pairs(listaTeleportes) do
                    if not autoFarmActive then break end
                    if Player.Character and Player.Character:FindFirstChild("HumanoidRootPart") then
                        pcall(function() Player.Character.HumanoidRootPart.CFrame = info.path.CFrame end)
                    end
                    task.wait(1.5)
                end
            end
        end
    end)

    autoBtn.MouseButton1Click:Connect(function()
        autoFarmActive = not autoFarmActive
        autoBtn.Text = autoFarmActive and "Automatização: LIGADO" or "Automatização: DESLIGADO"
        autoBtn.BackgroundColor3 = autoFarmActive and Color3.fromRGB(0, 200, 0) or Color3.fromRGB(200, 0, 0)
    end)

    -- Criar botões manuais
    local currentY = 80
    for _, info in pairs(listaTeleportes) do
        local btnM = Instance.new("TextButton", frame)
        btnM.Size = UDim2.new(0.85, 0, 0, 45)
        btnM.Position = UDim2.new(0.075, 0, 0, currentY)
        btnM.Text = info.nome
        btnM.BackgroundColor3 = Color3.fromRGB(200, 0, 0)
        btnM.TextColor3 = Color3.new(1, 1, 1)
        btnM.Font = Enum.Font.SourceSansBold
        Instance.new("UICorner", btnM).CornerRadius = UDim.new(0, 8)
        
        btnM.MouseButton1Click:Connect(function()
            if Player.Character and Player.Character:FindFirstChild("HumanoidRootPart") then
                pcall(function() Player.Character.HumanoidRootPart.CFrame = info.path.CFrame end)
            end
        end)
        currentY = currentY + 55
    end

    local closeBtn = Instance.new("TextButton", frame)
    closeBtn.Size = UDim2.fromOffset(30, 30)
    closeBtn.Position = UDim2.new(1, -35, 0, 5)
    closeBtn.Text = "X"
    closeBtn.BackgroundColor3 = Color3.new(1,0,0)
    closeBtn.MouseButton1Click:Connect(function() screenGui:Destroy() end)
end

-- Botão na aba JOGOS do Administrador Principal
btn(tabs.Jogos, "Escape da Lava (Lendas Brabas)", 10).MouseButton1Click:Connect(function()
    executarEscapeLava()
    print("Script Lendas Brabas executado!")
end)
